# Generated by Django 4.2.7 on 2024-01-15 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="AssignTrainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField(blank=True, null=True)),
                ("exp_date", models.DateField(blank=True, null=True)),
                ("Iinitaial_amount", models.IntegerField(blank=True, null=True)),
                ("pending_amount", models.IntegerField(blank=True, null=True)),
                ("total_paid_amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BA_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "verbose_name_plural": "Bussiness admin status",
            },
        ),
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BussinessOwnerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gym_name", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="pictures"),
                ),
                ("phone", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profilepics"),
                ),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("is_bussiness_admin", models.BooleanField(default=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.ba_status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=25)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="Profile_pic"),
                ),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "id_proof_imagee",
                    models.ImageField(blank=True, null=True, upload_to="ID Proofs"),
                ),
                ("disease", models.BooleanField(default=False)),
                (
                    "disease_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extendedbusiness",
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "blood_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bloodgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ID_Proof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrefferedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=10, null=True)),
                ("count", models.IntegerField(default=0)),
                ("remaining_count", models.IntegerField(blank=True, null=True)),
                ("reset_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Specializations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_specializations", models.TextField(blank=True, null=True)),
                ("other_certifications", models.TextField(blank=True, null=True)),
                ("year_of_experience", models.IntegerField(blank=True, null=True)),
                ("education_background", models.TextField(blank=True, null=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="certifications",
                        to="gym_app.certifications",
                    ),
                ),
                (
                    "extended_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer",
                        to="gym_app.extendedusermodel",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specializations",
                        to="gym_app.specializations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_date", models.DateField()),
                ("from_timing", models.TimeField()),
                ("to_timingg", models.TimeField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.extendedusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slot_Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countt", models.IntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(blank=True, max_length=20, null=True)),
                ("schedule_date", models.DateField(blank=True, null=True)),
                ("time_slot_field", models.TimeField(blank=True, null=True)),
                (
                    "workout_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "added_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "admin_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_member",
                        to="gym_app.extendedusermodel",
                    ),
                ),
                (
                    "members",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="gym_app.assigntrainer",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=2,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.schedulestatus",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.extendedusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary_management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_date", models.DateField()),
                ("salary", models.FloatField(default=0)),
                ("insentive", models.FloatField(default=0)),
                ("paid", models.FloatField(default=0)),
                ("balance", models.FloatField(blank=True, default=0, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salarymanagement",
                        to="gym_app.extendedusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("features", models.TextField()),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.activitylevel",
                    ),
                ),
                (
                    "cextended_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="gym_app.extendedusermodel",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.goal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.gender",
            ),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="id_prooff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.id_proof",
            ),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="preferred_time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.prefferedtime",
            ),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gym_app.role"
            ),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.status",
            ),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extendeduser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Equipements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("img", models.ImageField(upload_to="pictures")),
                ("desc", models.TextField(blank=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("expected_join_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiry",
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "memebership_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.membershipplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calorie_intake", models.FloatField(null=True)),
                ("goal", models.CharField(blank=True, max_length=20, null=True)),
                ("meal_options", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "added_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "admin_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.extendedusermodel",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietmember",
                        to="gym_app.assigntrainer",
                        verbose_name="Trainer Member",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        default=2,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.schedulestatus",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diettrainer",
                        to="gym_app.extendedusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonDietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breakfast", models.TextField()),
                ("snack_mrng", models.TextField()),
                ("lunch", models.TextField()),
                ("snack", models.TextField()),
                ("dinner", models.TextField()),
                ("optional_beverages", models.TextField()),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commontrainer",
                        to="gym_app.extendedusermodel",
                    ),
                ),
                (
                    "added_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.bussinessownermodel",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym_app.week"
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goalcommon",
                        to="gym_app.goal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        max_length=10,
                    ),
                ),
                ("attendance_date", models.DateField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.extendedusermodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assigntrainer",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignmember",
                to="gym_app.extendedusermodel",
            ),
        ),
        migrations.AddField(
            model_name="assigntrainer",
            name="membership_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.membershipplan",
            ),
        ),
        migrations.AddField(
            model_name="assigntrainer",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigntrainer",
                to="gym_app.extendedusermodel",
            ),
        ),
    ]
