# Generated by Django 4.2.1 on 2023-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField(blank=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
