# Generated by Django 4.2.7 on 2024-01-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym_app", "0002_alter_bussinessownermodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bussinessownermodel",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default="Activate",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gym_app.ba_status",
            ),
        ),
    ]
