# Generated by Django 4.2.7 on 2024-01-24 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym_app", "0003_alter_bussinessownermodel_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberprofile",
            old_name="cextended_user",
            new_name="extended_user",
        ),
    ]
