# Generated by Django 4.2.1 on 2023-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_bloodgroup_gender_prefferedtime_role_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BA_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
