# Generated by Django 4.2.1 on 2023-05-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_ba_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessownermodel',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.ba_status'),
        ),
    ]
