# Generated by Django 4.2.1 on 2023-05-31 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_assigntrainer_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='gym_app.bussinessownermodel'),
        ),
    ]
