# Generated by Django 4.2.1 on 2023-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_enquiry_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ba_status',
            options={'verbose_name_plural': 'Bussiness admin status'},
        ),
        migrations.AddField(
            model_name='bussinessownermodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
