# Generated by Django 4.2.1 on 2023-06-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0015_week_schedule_customizedplan_commondietplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondietplan',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commontrainer', to='gym_app.extendedusermodel'),
        ),
        migrations.AlterField(
            model_name='assigntrainer',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignmember', to='gym_app.extendedusermodel'),
        ),
    ]
