# Generated by Django 4.2.1 on 2023-07-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0022_slotbooking_remaining_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='remaining_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
