# Generated by Django 4.2.1 on 2023-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0024_remove_slotbooking_remaining_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefferedtime',
            name='remaining_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
