# Generated by Django 4.2.1 on 2023-07-07 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0025_prefferedtime_remaining_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 7, 7)),
        ),
    ]
