# Generated by Django 4.2.1 on 2023-07-11 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0027_auto_20230710_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipements',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
    ]
