# Generated by Django 4.2.1 on 2023-07-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0029_slot_count_alter_prefferedtime_reset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='shift',
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym_app.slot_count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='from_timing',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='to_timingg',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot_count',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
