# Generated by Django 4.2.1 on 2023-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0030_remove_slotbooking_shift_slotbooking_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='count',
        ),
    ]
