# Generated by Django 4.2.1 on 2023-07-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0031_remove_slotbooking_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='slot_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym_app.slot_count'),
            preserve_default=False,
        ),
    ]
