# Generated by Django 4.2.1 on 2023-07-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0032_slotbooking_slot_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot_count',
            old_name='count',
            new_name='countt',
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='slot_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym_app.slot_count'),
        ),
    ]
