# Generated by Django 3.2.9 on 2023-07-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0036_auto_20230722_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondietplan',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.bussinessownermodel'),
        ),
    ]
