# Generated by Django 4.2.1 on 2023-07-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0038_customizedplan_added_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedplan',
            name='added_by_admin',
        ),
    ]
