# Generated by Django 3.2.9 on 2023-07-25 05:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0039_remove_customizedplan_added_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedplan',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.bussinessownermodel'),
        ),
        migrations.AddField(
            model_name='customizedplan',
            name='admin_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.extendedusermodel'),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 7, 25)),
        ),
    ]
