# Generated by Django 3.2.9 on 2023-07-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0040_auto_20230725_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedplan',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diettrainer', to='gym_app.extendedusermodel'),
        ),
    ]
