# Generated by Django 3.2.9 on 2023-07-27 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0041_alter_customizedplan_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customizedplan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmember', to='gym_app.assigntrainer', verbose_name='Trainer Member'),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 7, 27)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
