# Generated by Django 3.2.9 on 2023-07-28 04:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0042_auto_20230727_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='added_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.bussinessownermodel'),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
    ]
