# Generated by Django 3.2.9 on 2023-07-28 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0043_auto_20230728_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.extendedusermodel'),
        ),
    ]
