# Generated by Django 4.2.1 on 2023-07-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0044_alter_schedule_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='members',
        ),
        migrations.AddField(
            model_name='schedule',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gym_app.assigntrainer'),
        ),
    ]
