# Generated by Django 4.2.1 on 2023-07-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0045_remove_schedule_members_schedule_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='admin_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_member', to='gym_app.extendedusermodel'),
        ),
    ]
