# Generated by Django 4.2.1 on 2023-07-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0046_schedule_admin_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='memebership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.membershipplan'),
        ),
    ]
