# Generated by Django 4.2.1 on 2023-08-04 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0050_extendedusermodel_id_proof_imagee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='profie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_pic'),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
    ]
