# Generated by Django 4.2.1 on 2023-08-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0051_extendedusermodel_profie_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedusermodel',
            old_name='profie_pic',
            new_name='profile_pic',
        ),
    ]
