# Generated by Django 4.2.1 on 2023-08-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0052_rename_profie_pic_extendedusermodel_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('salary', models.FloatField()),
                ('insentive', models.FloatField()),
                ('paid', models.FloatField()),
                ('balance', models.FloatField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarymanagement', to='gym_app.extendedusermodel')),
            ],
        ),
    ]
