# Generated by Django 4.2.1 on 2023-08-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0053_salary_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_management',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.bussinessownermodel'),
        ),
    ]
