# Generated by Django 4.2.1 on 2023-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0054_salary_management_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_management',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary_management',
            name='insentive',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary_management',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary_management',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
