# Generated by Django 3.2.9 on 2023-08-09 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0058_salary_management_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='expected_join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 9)),
        ),
    ]
