# Generated by Django 3.2.9 on 2023-08-11 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0059_auto_20230809_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Standard', 'Standard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 11)),
        ),
    ]
