# Generated by Django 3.2.9 on 2023-08-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0060_auto_20230811_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
