# Generated by Django 4.2.1 on 2023-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0062_goal_added_by'),
    ]

    operations = [
        
    ]
