# Generated by Django 3.2.9 on 2023-08-14 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0063_assigntrainer_total_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 14)),
        ),
    ]
