# Generated by Django 4.2.1 on 2023-08-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0065_alter_prefferedtime_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntrainer',
            name='total_paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
