# Generated by Django 4.2.1 on 2023-11-17 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0066_assigntrainer_total_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='slot_count',
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 11, 17)),
        ),
    ]
